name: Publish Python Package

on:
  release:
    types: [ created ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install Dependencies
        run: |
          python --version
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel twine
      - name: Run Unit Tests
        run: |
          python -m unittest discover -v -f ./tests
      - name: Build and Package
        run: |
          pip freeze
          python setup.py sdist bdist_wheel
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_UPLOAD_TOKEN }}
          verbose: true
